log_level = "INFO"

##### Devices #####
# !!! IMPORTANT NOTE !!!
# Virtual device name should start with 'EvdevProxy' prefix, otherwise default
# udev rules from '70-uinput-evdev-proxy.rules' won't create device symlink in
# '/dev/input/by-id/' directory. If you want to use another name make sure to
# configure udev accordingly.
#
# Available device types:
#  * Simple -- Single virtual device that capture and proxy all devices that
#              match any of it's selectors
#    Parameters:
#      * vendor (int)     -- 16-bit device vendor ID
#      * model (int)      -- 16-bit model vendor ID
#      * class (enum)     -- device class (Mouse/Keyboard/AIO),
#                            AIO - all-in-one, device that acts both as KB
#                            and Mouse
#      * selector (array) -- list of selectors that specify criteria used to
#                            select witch real evdev devices this virtual
#                            device should proxy
#
#    Available device selectors:
#      * USBID      -- Simple selector that blindly selects usb device based
#                      on it's usb vendor:model identificator
#      * USBIDClass -- Simple selector that blindly selects usb device based
#                      on it's usb vendor:model identificator and device
#                      class (Mouse/Keyboard), useful for wireless devices
#                      with single receiver (e.g. Logitech Unifying Receiver)
#

[[device]]
[device.Simple]
name = "EvdevProxyAIO"
vendor = 0x1337
model = 0x1337
class = "AIO"

# JosefAdamcik Sofle
[[device.Simple.selector]]
USBIDClass = { vendor = 0xfc32, model = 0x0287, class = 'Mouse' }
[[device.Simple.selector]]
USBIDClass = { vendor = 0xfc32, model = 0x0287, class = 'Keyboard' }

# Kensington ORBIT WIRELESS TB Consumer Control
[[device.Simple.selector]]
USBIDClass = { vendor = 0x047d, model = 0x80a6, class = 'Mouse' }
[[device.Simple.selector]]
USBIDClass = { vendor = 0x047d, model = 0x80a6, class = 'Keyboard' }

# Kensington SlimBlade Pro(2.4GHz Receiver) Kensington SlimBlade Pro Trackball(2.4GHz Receiver)
[[device.Simple.selector]]
USBIDClass = { vendor = 0x047d, model = 0x80d6, class = 'Mouse' }
[[device.Simple.selector]]
USBIDClass = { vendor = 0x047d, model = 0x80d6, class = 'Keyboard' }

# Keychron Keychron K7
[[device.Simple.selector]]
USBID = { vendor = 0x05ac, model = 0x0250 }
[[device.Simple.selector]]
Bus = { bus = "bluetooth", device_group = "5/5ac/250:0c:7a:15:a9:81:d8" }

# Razer Razer Mamba Elite
[[device.Simple.selector]]
USBIDClass = { vendor = 0x1532, model = 0x006c, class = 'Mouse' }
[[device.Simple.selector]]
USBIDClass = { vendor = 0x1532, model = 0x006c, class = 'Keyboard' }
